name: Node.js CI with Yarn

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Yarn
      run: |
        npm install -g yarn
    - run: yarn install --frozen-lockfile
    - run: yarn build --if-present
    - run: yarn test
